export default {
  light: {
    text: "#000",
    background: "#fff",
    gray: "#696969",
    tint: "#000",
    tabIconDefault: "#ccc",
    tabIconSelected: "#000",
    blue: "#028efd",
    green: "#4fe3c1",
    red: "#fd5632",
    border: "#000",
  },
  dark: {
    text: "#fff",
    background: "#000",
    gray: "#d3d3d3",
    tint: "#fff",
    tabIconDefault: "#ccc",
    tabIconSelected: "#fff",
    blue: "#43adff",
    green: "#75ffe1",
    red: "#fe8b78",
    border: "#fff",
  },
};
